# Generated by Django 3.0.3 on 2020-02-23 09:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='URLData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetURL', models.CharField(max_length=256)),
                ('shortenURL', models.CharField(max_length=128)),
                ('dateCreated', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 9, 46, 24, 99314))),
                ('dateExpired', models.DateTimeField(default=datetime.datetime(2020, 2, 23, 10, 1, 24, 99345))),
                ('status', models.CharField(default='ACTIVE', max_length=64)),
                ('shortURLbase', models.CharField(default='a', max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='ShortURLAnalytics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('targetURL', models.CharField(max_length=256)),
                ('shortenURL', models.CharField(max_length=128)),
                ('IPAddr', models.CharField(max_length=32)),
                ('count_of_hits', models.IntegerField(default=0)),
                ('URLid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='url_shortning.URLData')),
            ],
        ),
    ]
