# Generated by Django 3.0.3 on 2020-02-23 11:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('url_shortning', '0003_auto_20200223_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urldata',
            name='dateCreated',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 11, 32, 633958)),
        ),
        migrations.AlterField(
            model_name='urldata',
            name='dateExpired',
            field=models.DateTimeField(default=datetime.datetime(2020, 2, 23, 11, 26, 32, 634023)),
        ),
    ]
